# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy

# varid (variable id, primary key), variable (siemens), url (https://uk.investing.com/equities/siemens), symbid (350)
class FinancialscraperItem(scrapy.Item):
    # define the fields for your item here like:
    variable = scrapy.Field()
    url = scrapy.Field()
    symbid = scrapy.Field()
    Freq = scrapy.Field()
    
class GetincomestatementItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    Symb = scrapy.Field()
    Freq = scrapy.Field()
    Date = scrapy.Field()
    Total_Revenue = scrapy.Field()
    Revenue = scrapy.Field()
    Other_Revenue_Total = scrapy.Field()
    Cost_of_Revenue_Total = scrapy.Field()
    Gross_Profit = scrapy.Field()
    Total_Operating_Expenses = scrapy.Field()
    Selling_General_Admin_Expenses_Total = scrapy.Field()
    Research_Development = scrapy.Field()
    Depreciation_Amortization = scrapy.Field()
    Interest_Expense_Income_Net_Operating = scrapy.Field()
    Unusual_Expense_Income = scrapy.Field()
    Other_Operating_Expenses_Total = scrapy.Field()
    Operating_Income = scrapy.Field()
    Interest_Income_Expense_Net_Non_Operating = scrapy.Field()
    Gain_Loss_on_Sale_of_Assets = scrapy.Field()
    Other_Net = scrapy.Field()
    Net_Income_Before_Taxes = scrapy.Field()
    Provision_for_Income_Taxes = scrapy.Field()
    Net_Income_After_Taxes = scrapy.Field()
    Minority_Interest = scrapy.Field()
    Equity_In_Affiliates = scrapy.Field()
    US_GAAP_Adjustment = scrapy.Field()
    Net_Income_Before_Extraordinary_Items = scrapy.Field()
    Total_Extraordinary_Items = scrapy.Field()
    Net_Income = scrapy.Field()
    Total_Adjustments_to_Net_Income = scrapy.Field()
    Income_Available_to_Common_Excluding_Extraordinary_Items = scrapy.Field()
    Dilution_Adjustment = scrapy.Field()
    Diluted_Net_Income = scrapy.Field()
    Diluted_Weighted_Average_Shares = scrapy.Field()
    Diluted_EPS_Excluding_Extraordinary_Items = scrapy.Field()
    DPS_Common_Stock_Primary_Issue = scrapy.Field()
    Diluted_Normalized_EPS = scrapy.Field()

class GetbalancesheetItem(scrapy.Item):

    Symb = scrapy.Field()
    Freq = scrapy.Field()
    Date = scrapy.Field()
    Total_Current_Assets = scrapy.Field()
    Cashand_Short_Term_Investments = scrapy.Field()
    Cash = scrapy.Field()
    Cash_Equivalents = scrapy.Field()
    Short_Term_Investments = scrapy.Field()
    Total_Receivables_Net = scrapy.Field()
    Accounts_Receivables_TradeNet = scrapy.Field()
    Total_Inventory = scrapy.Field()
    Prepaid_Expenses = scrapy.Field()
    Other_Current_Assets_Total = scrapy.Field()
    Total_Assets = scrapy.Field()
    Property_Plant_Equipment_Total_Net = scrapy.Field()
    Property_Plant_Equipment_Total_Gross = scrapy.Field()
    Accumulated_Depreciation_Total = scrapy.Field()
    Goodwill_Net = scrapy.Field()
    Intangibles_Net = scrapy.Field()
    Long_Term_Investments = scrapy.Field()
    Note_Receivable_Long_Term = scrapy.Field()
    Other_Long_Term_Assets_Total = scrapy.Field()
    Other_Assets_Total = scrapy.Field()
    Total_Current_Liabilities = scrapy.Field()
    Accounts_Payable = scrapy.Field()
    Payable_Accrued = scrapy.Field()
    Accrued_Expenses = scrapy.Field()
    Notes_Payable_Short_Term_Debt = scrapy.Field()
    Current_Portof_LT_Debt_Capital_Leases = scrapy.Field()
    Other_Current_liabilities_Total = scrapy.Field()
    Total_Liabilities = scrapy.Field()
    Total_Long_Term_Debt = scrapy.Field()
    Long_Term_Debt = scrapy.Field()
    Capital_Lease_Obligations = scrapy.Field()
    Total_Debt = scrapy.Field()
    Deferred_Income_Tax = scrapy.Field()
    Minority_Interest = scrapy.Field()
    Other_Liabilities_Total = scrapy.Field()
    Total_Equity = scrapy.Field()
    Redeemable_Preferred_Stock_Total = scrapy.Field()
    Preferred_Stock_Non_Redeemable_Net = scrapy.Field()
    Common_Stock_Total = scrapy.Field()
    Additional_Paid_In_Capital = scrapy.Field()
    Retained_Earnings_Accumulated_Deficit = scrapy.Field()
    Treasury_Stock_Common = scrapy.Field()
    ESOP_Debt_Guarantee = scrapy.Field()
    Unrealized_Gain_Loss = scrapy.Field()
    Other_Equity_Total = scrapy.Field()
    Total_Liabilities_Shareholders_Equity = scrapy.Field()
    Total_Common_Shares_Outstanding = scrapy.Field()
    Total_Preferred_Shares_Outstanding = scrapy.Field()

class GetcashflowItem(scrapy.Item):

    Symb = scrapy.Field()
    Freq = scrapy.Field()
    Date = scrapy.Field()
    Period_Length = scrapy.Field()
    Net_Incom_Starting_Line = scrapy.Field()
    Cash_From_Operating_Activities = scrapy.Field()
    Depreciation_Depletion = scrapy.Field()
    Amortization = scrapy.Field()
    Deferred_Taxes = scrapy.Field()
    Non_Cash_Items = scrapy.Field()
    Cash_Receipts = scrapy.Field()
    Cash_Payments = scrapy.Field()
    Cash_Taxes_Paid = scrapy.Field()
    Cash_Interest_Paid = scrapy.Field()
    Changesin_Working_Capital = scrapy.Field()
    Cash_From_Investing_Activities = scrapy.Field()
    Capital_Expenditures = scrapy.Field()
    Other_Investing_Cash_Flow_Items_Total = scrapy.Field()
    Cash_From_Financing_Activities = scrapy.Field()
    Financing_Cash_Flow_Items = scrapy.Field()
    Total_Cash_Dividends_Paid = scrapy.Field()
    Issuance_Retirementof_Stock_Net = scrapy.Field()
    Issuance_Retirementof_DebtNet = scrapy.Field()
    Foreign_Exchange_Effects = scrapy.Field()
    Net_Changein_Cash = scrapy.Field()


